# Generated by Django 3.1.2 on 2021-02-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beeword',
            options={'managed': True},
        ),
    ]
