# Generated by Django 3.1.7 on 2021-02-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbee', '0002_auto_20210228_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beeword',
            options={},
        ),
        migrations.AlterModelTable(
            name='beeword',
            table='beeword_tb',
        ),
    ]
